"""initial migration

Revision ID: 508586b7424f
Revises: 
Create Date: 2026-08-27 13:04:57.436727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508586b7424f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('native_pronounciation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('passport_img', sa.String(), nullable=False),
    sa.Column('safety_level', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('native_pronounciation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('no_of_seasons', sa.Integer(), nullable=True),
    sa.Column('no_of_episodes', sa.Integer(), nullable=True),
    sa.Column('ep_time', sa.Integer(), nullable=True),
    sa.Column('film_category', sa.String(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('featuring', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag_type', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tag_type', name='uq_tag_name_type')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries_continents',
    sa.Column('continents_id', sa.Integer(), nullable=False),
    sa.Column('countries_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['continents_id'], ['continents.id'], name=op.f('fk_countries_continents_continents_id_continents')),
    sa.ForeignKeyConstraint(['countries_id'], ['countries.id'], name=op.f('fk_countries_continents_countries_id_countries')),
    sa.PrimaryKeyConstraint('continents_id', 'countries_id')
    )
    op.create_table('countries_languages',
    sa.Column('countries_id', sa.Integer(), nullable=False),
    sa.Column('languages_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['countries_id'], ['countries.id'], name=op.f('fk_countries_languages_countries_id_countries')),
    sa.ForeignKeyConstraint(['languages_id'], ['languages.id'], name=op.f('fk_countries_languages_languages_id_languages')),
    sa.PrimaryKeyConstraint('countries_id', 'languages_id')
    )
    op.create_table('country_media',
    sa.Column('countries_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['countries_id'], ['countries.id'], name=op.f('fk_country_media_countries_id_countries')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_country_media_media_id_media')),
    sa.PrimaryKeyConstraint('countries_id', 'media_id')
    )
    op.create_table('other_locations',
    sa.Column('admin_level', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('parent_location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('native_pronounciation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_other_locations_country_id_countries')),
    sa.ForeignKeyConstraint(['parent_location_id'], ['other_locations.id'], name=op.f('fk_other_locations_parent_location_id_other_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlists_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_businesses_country_id_countries')),
    sa.ForeignKeyConstraint(['location_id'], ['other_locations.id'], name=op.f('fk_businesses_location_id_other_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notable_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('parent_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['other_locations.id'], name=op.f('fk_notable_events_location_id_other_locations')),
    sa.ForeignKeyConstraint(['parent_event_id'], ['notable_events.id'], name=op.f('fk_notable_events_parent_event_id_notable_events')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_sites_country_id_countries')),
    sa.ForeignKeyConstraint(['location_id'], ['other_locations.id'], name=op.f('fk_sites_location_id_other_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries_events',
    sa.Column('countries_id', sa.Integer(), nullable=False),
    sa.Column('notable_events_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['countries_id'], ['countries.id'], name=op.f('fk_countries_events_countries_id_countries')),
    sa.ForeignKeyConstraint(['notable_events_id'], ['notable_events.id'], name=op.f('fk_countries_events_notable_events_id_notable_events')),
    sa.PrimaryKeyConstraint('countries_id', 'notable_events_id')
    )
    op.create_table('sites_interests',
    sa.Column('sites_id', sa.Integer(), nullable=False),
    sa.Column('interests_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interests_id'], ['interests.id'], name=op.f('fk_sites_interests_interests_id_interests')),
    sa.ForeignKeyConstraint(['sites_id'], ['sites.id'], name=op.f('fk_sites_interests_sites_id_sites')),
    sa.PrimaryKeyConstraint('sites_id', 'interests_id')
    )
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_wishlist_items_business_id_businesses')),
    sa.ForeignKeyConstraint(['continent_id'], ['continents.id'], name=op.f('fk_wishlist_items_continent_id_continents')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_wishlist_items_country_id_countries')),
    sa.ForeignKeyConstraint(['location_id'], ['other_locations.id'], name=op.f('fk_wishlist_items_location_id_other_locations')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_wishlist_items_site_id_sites')),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], name=op.f('fk_wishlist_items_wishlist_id_wishlists')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist_items_tags',
    sa.Column('wishlist_items_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], name=op.f('fk_wishlist_items_tags_tags_id_tags')),
    sa.ForeignKeyConstraint(['wishlist_items_id'], ['wishlist_items.id'], name=op.f('fk_wishlist_items_tags_wishlist_items_id_wishlist_items')),
    sa.PrimaryKeyConstraint('wishlist_items_id', 'tags_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_items_tags')
    op.drop_table('wishlist_items')
    op.drop_table('sites_interests')
    op.drop_table('countries_events')
    op.drop_table('sites')
    op.drop_table('notable_events')
    op.drop_table('businesses')
    op.drop_table('wishlists')
    op.drop_table('other_locations')
    op.drop_table('country_media')
    op.drop_table('countries_languages')
    op.drop_table('countries_continents')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('media')
    op.drop_table('languages')
    op.drop_table('interests')
    op.drop_table('countries')
    op.drop_table('continents')
    # ### end Alembic commands ###
