"""initial migration

Revision ID: 57d8db3afb38
Revises: 
Create Date: 2026-08-22 19:28:41.780458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d8db3afb38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('native_pronounciation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('passport_img', sa.String(), nullable=False),
    sa.Column('safety_level', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('native_pronounciation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries_continents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['continent_id'], ['continents.id'], name=op.f('fk_countries_continents_continent_id_continents')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_countries_continents_country_id_countries')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_countries_languages_country_id_countries')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_countries_languages_language_id_languages')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries_languages')
    op.drop_table('countries_continents')
    op.drop_table('languages')
    op.drop_table('countries')
    op.drop_table('continents')
    # ### end Alembic commands ###
