"""add country table

Revision ID: 9a5330747e97
Revises: 6f72763ac877
Create Date: 2026-08-22 18:55:43.740286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5330747e97'
down_revision = '6f72763ac877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('passport_img', sa.String(), nullable=False),
    sa.Column('safety_level', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('native_pronounciation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries_continents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['continent_id'], ['continents.id'], name=op.f('fk_countries_continents_continent_id_continents')),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_countries_continents_country_id_countries')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('continents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('native_pronounciation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('continents', schema=None) as batch_op:
        batch_op.drop_column('native_pronounciation')
        batch_op.drop_column('native_name')

    op.drop_table('countries_continents')
    op.drop_table('countries')
    # ### end Alembic commands ###
