"""create other location model

Revision ID: de9f044d3865
Revises: 57d8db3afb38
Create Date: 2026-08-23 09:29:07.007493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9f044d3865'
down_revision = '57d8db3afb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_locations',
    sa.Column('admin_level', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('parent_location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('native_name', sa.String(), nullable=True),
    sa.Column('native_pronounciation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_other_locations_country_id_countries')),
    sa.ForeignKeyConstraint(['parent_location_id'], ['other_locations.id'], name=op.f('fk_other_locations_parent_location_id_other_locations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_locations')
    # ### end Alembic commands ###
